       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                H3O1C6Br3

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  H     1    1.00782      -2.9579243300      -0.1456951000      -0.0645700200
  O     8   15.99491      -2.4140263300       0.6533289600       0.0167861400
  C     6   12.00000      -1.1162538600       0.3001961300       0.0316804700
  C     6   12.00000      -0.1751860300       1.3265276400       0.1442030300
  C     6   12.00000      -0.6484066600      -1.0109303400      -0.0568526300
 Br    35   78.91834      -0.7340312300       3.1621727600       0.2713225100
  C     6   12.00000       1.1819985600       1.0636034000       0.1682242000
 Br    35   78.91834      -1.9020357800      -2.4688026900      -0.2139455900
  C     6   12.00000       0.7011102700      -1.3131691200      -0.0362055100
  H     1    1.00782       1.9117967000       1.8758018100       0.2567785200
  C     6   12.00000       1.5883128600      -0.2580878900       0.0768236400
  H     1    1.00782       1.0504991600      -2.3486136800      -0.1067889400
 Br    35   78.91834       3.4780533700      -0.6438808700       0.1087191700
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     1.00000
                          The frequencies number:          33
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.14100999      0.04585448      0.05307657

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x      1397.89327        14.94170       -46.97201
    y        14.94170      1466.54518      -109.57317
    z       -46.97201      -109.57317      2843.94937

              Principal moments of inertia (amu*A**2): 
            2854.19391000        1394.34125000        1459.85266000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation             5822691.85721       The ln(Q)   15.57727

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       33.93607  (cal/mol*K)    141.98852    (J/mol*K)         0.00005408  (hartree/K)
  G rotation       -9.22931   (kcal/mol)    -38.61544     (kJ/mol)        -0.01470783    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   327.77340   amu

              *****      Translation thermodynamic functions     ******

  Q translation           233246855.62381       The ln(Q)   19.26761
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       43.25673  (cal/mol*K)    180.98618    (J/mol*K)         0.00006893  (hartree/K)
  G translation      -11.41578   (kcal/mol)    -47.76363     (kJ/mol)        -0.01819219    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : Harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   33
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   33


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       68.480          68.480         yes       3.55355    0.098        0.598        4.197       -0.653        1.969
  2      105.310         105.310         yes       2.50993    0.151        0.605        3.354       -0.395        1.945
  3      107.950         107.950         yes       2.46285    0.154        0.606        3.305       -0.380        1.943
  4      120.810         120.810         yes       2.26361    0.173        0.609        3.087       -0.311        1.932
  5      164.410         164.410         yes       1.82585    0.235        0.623        2.498       -0.122        1.886
  6      239.040         239.040         yes       1.46097    0.342        0.657        1.810        0.117        1.781
  7      278.320         278.320         yes       1.35325    0.398        0.679        1.544        0.219        1.714
  8      291.150         291.150         yes       1.32515    0.416        0.687        1.467        0.249        1.690
  9      308.890         308.890         yes       1.29072    0.442        0.698        1.368        0.290        1.657
 10      335.400         335.400         yes       1.24718    0.479        0.717        1.234        0.349        1.605
 11      353.510         353.510         yes       1.22190    0.505        0.730        1.151        0.387        1.568
 12      487.760         487.760         yes       1.10498    0.697        0.844        0.689        0.638        1.277
 13      531.130         531.130         yes       1.08350    0.759        0.886        0.585        0.712        1.181
 14      537.180         537.180         yes       1.08091    0.768        0.892        0.571        0.722        1.168
 15      671.740         671.740         yes       1.04069    0.960        1.038        0.341        0.937        0.884
 16      713.740         713.740         yes       1.03298    1.020        1.088        0.290        1.001        0.803
 17      719.930         719.930         yes       1.03198    1.029        1.095        0.283        1.011        0.792
 18      873.210         873.210         yes       1.01501    1.248        1.286        0.155        1.239        0.538
 19      943.360         943.360         yes       1.01065    1.349        1.377        0.117        1.342        0.443
 20      950.030         950.030         yes       1.01031    1.358        1.386        0.114        1.352        0.435
 21     1099.250        1099.250         yes       1.00499    1.571        1.587        0.063        1.569        0.281
 22     1168.430        1168.430         yes       1.00357    1.670        1.682        0.047        1.668        0.226
 23     1201.710        1201.710         yes       1.00304    1.718        1.728        0.041        1.716        0.204
 24     1272.710        1272.710         yes       1.00216    1.819        1.827        0.031        1.818        0.162
 25     1382.280        1382.280         yes       1.00127    1.976        1.981        0.019        1.975        0.112
 26     1428.250        1428.250         yes       1.00102    2.042        2.046        0.016        2.041        0.096
 27     1523.750        1523.750         yes       1.00064    2.178        2.181        0.011        2.178        0.069
 28     1656.650        1656.650         yes       1.00034    2.368        2.370        0.006        2.368        0.043
 29     1732.080        1732.080         yes       1.00023    2.476        2.477        0.004        2.476        0.033
 30     1756.390        1756.390         yes       1.00021    2.511        2.512        0.004        2.511        0.030
 31     3053.570        3053.570         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 32     3057.550        3057.550         yes       1.00000    4.371        4.371        0.000        4.371        0.000
 33     3223.520        3223.520         yes       1.00000    4.608        4.608        0.000        4.608        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                 708.39128       The ln(Q)    6.56300
    H vibration       50.83770   (kcal/mol)    212.70494     (kJ/mol)         0.08101496    (hartree)
    U vibration       50.83770   (kcal/mol)    212.70494     (kJ/mol)         0.08101496    (hartree)
           ZPE        46.25735   (kcal/mol)    193.54077     (kJ/mol)         0.07371572    (hartree)
    S vibration       28.40459  (cal/mol*K)    118.84481    (J/mol*K)         0.00004527  (hartree/K)
   Cv vibration       28.46655  (cal/mol*K)    119.10404    (J/mol*K)         0.00004536  (hartree/K)
    G vibration       42.36887   (kcal/mol)    177.27136     (kJ/mol)         0.06751904    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total  962083604353575168.00000       The ln(Q)   45.09821
        H total       53.20764   (kcal/mol)    222.62078     (kJ/mol)         0.08479170    (hartree)
        U total       52.61516   (kcal/mol)    220.14182     (kJ/mol)         0.08384752    (hartree)
       Cv total       34.42817  (cal/mol*K)    144.04746    (J/mol*K)         0.00005486  (hartree/K)
           ZPE        46.25735   (kcal/mol)    193.54077     (kJ/mol)         0.07371572    (hartree)
        S total      105.59740  (cal/mol*K)    441.81951    (J/mol*K)         0.00016828  (hartree/K)
        G total       22.31627   (kcal/mol)     93.37126     (kJ/mol)         0.03556320    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08384752 (hartree)
                       Thermal correction to Enthalpy :   0.08479170 
              Thermal correction to Gibbs Free Energy :   0.03461902 (hartree)
              ZPE correction to the Electronic Energy :   0.07371572 (hartree)


