       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                   C5O3H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -1.2964350000       0.2812370000       0.0903870000
  O     8   15.99491      -1.2133700000      -1.0562340000       0.3720550000
  O     8   15.99491      -0.1764580000       0.6862310000      -0.5835190000
  O     8   15.99491      -2.2153830000       0.9898200000       0.3896670000
  C     6   12.00000      -0.0669900000      -1.6108010000      -0.2768840000
  C     6   12.00000       0.8006380000      -0.3757330000      -0.5920950000
  H     1    1.00782       0.4295040000      -2.3238740000       0.4103390000
  H     1    1.00782      -0.3879960000      -2.1520180000      -1.1928560000
  C     6   12.00000       1.8990640000      -0.1027820000       0.4331600000
  H     1    1.00782       1.2275270000      -0.4166410000      -1.6157820000
  H     1    1.00782       1.4404600000      -0.1230280000       1.4465720000
  H     1    1.00782       2.6087770000      -0.9584650000       0.3957930000
  C     6   12.00000       2.6315050000       1.2170210000       0.2005230000
  H     1    1.00782       3.4020920000       1.3905580000       0.9768670000
  H     1    1.00782       3.1380860000       1.2280740000      -0.7868850000
  H     1    1.00782       1.9218360000       2.0670020000       0.2230270000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     1.01100
                          The frequencies number:          42
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.03305943      0.01312180      0.00833617

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       137.88570       -22.11327         7.00399
    y       -22.11327       319.00764        -6.78965
    z         7.00399        -6.78965       404.53834

              Principal moments of inertia (amu*A**2): 
             135.08477000         320.98281000         405.36410000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              320265.18840       The ln(Q)   12.67690

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.17244  (cal/mol*K)    117.87348    (J/mol*K)         0.00004490  (hartree/K)
  G rotation       -7.51088   (kcal/mol)    -31.42554     (kJ/mol)        -0.01196934    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   116.04734   amu

              *****      Translation thermodynamic functions     ******

  Q translation            49136933.44271       The ln(Q)   17.71012
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.16169  (cal/mol*K)    168.03650    (J/mol*K)         0.00006400  (hartree/K)
  G translation      -10.49299   (kcal/mol)    -43.90268     (kJ/mol)        -0.01672163    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU=  100 ALPHA=    4 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   42
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   42


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       71.900          72.691         yes       3.37994    0.104        0.362        3.370       -0.642        1.206
  2      128.020         129.428         yes       2.15279    0.185        0.529        2.861       -0.324        1.679
  3      152.570         154.248         yes       1.90491    0.221        0.571        2.590       -0.201        1.762
  4      225.920         228.405         yes       1.49731    0.327        0.639        1.897        0.073        1.769
  5      239.590         242.225         yes       1.45076    0.346        0.648        1.792        0.114        1.754
  6      375.020         379.145         yes       1.19115    0.542        0.747        1.045        0.435        1.512
  7      445.580         450.481         yes       1.12833    0.644        0.808        0.796        0.571        1.359
  8      530.300         536.133         yes       1.08135    0.766        0.890        0.574        0.719        1.170
  9      691.130         698.732         yes       1.03555    0.999        1.070        0.308        0.978        0.832
 10      729.150         737.171         yes       1.02935    1.054        1.115        0.265        1.036        0.760
 11      739.640         747.776         yes       1.02785    1.069        1.128        0.254        1.052        0.741
 12      797.530         806.303         yes       1.02085    1.153        1.201        0.202        1.140        0.640
 13      820.460         829.485         yes       1.01860    1.186        1.230        0.185        1.175        0.603
 14      881.710         891.409         yes       1.01373    1.274        1.309        0.145        1.266        0.512
 15      955.950         966.465         yes       1.00952    1.382        1.408        0.107        1.376        0.415
 16      974.720         985.442         yes       1.00868    1.409        1.433        0.099        1.404        0.393
 17      987.790         998.656         yes       1.00814    1.428        1.451        0.094        1.423        0.379
 18     1056.570        1068.192         yes       1.00581    1.527        1.545        0.071        1.524        0.308
 19     1074.260        1086.077         yes       1.00532    1.553        1.569        0.066        1.549        0.292
 20     1092.080        1104.093         yes       1.00488    1.578        1.594        0.061        1.575        0.277
 21     1105.800        1117.964         yes       1.00456    1.598        1.613        0.058        1.595        0.265
 22     1134.280        1146.757         yes       1.00397    1.639        1.652        0.052        1.637        0.242
 23     1195.750        1208.903         yes       1.00294    1.728        1.738        0.040        1.726        0.199
 24     1245.980        1259.686         yes       1.00230    1.801        1.809        0.032        1.799        0.169
 25     1261.800        1275.680         yes       1.00213    1.824        1.831        0.030        1.822        0.160
 26     1303.210        1317.545         yes       1.00174    1.884        1.890        0.025        1.882        0.140
 27     1340.250        1354.993         yes       1.00145    1.937        1.943        0.022        1.936        0.123
 28     1355.470        1370.380         yes       1.00134    1.959        1.964        0.020        1.958        0.117
 29     1357.830        1372.766         yes       1.00133    1.962        1.968        0.020        1.962        0.116
 30     1402.520        1417.948         yes       1.00107    2.027        2.031        0.017        2.026        0.100
 31     1418.790        1434.397         yes       1.00099    2.051        2.055        0.016        2.050        0.094
 32     1431.860        1447.610         yes       1.00093    2.069        2.073        0.015        2.069        0.090
 33     1446.210        1462.118         yes       1.00086    2.090        2.094        0.014        2.090        0.085
 34     1902.630        1923.559         yes       1.00009    2.750        2.750        0.002        2.750        0.016
 35     2962.930        2995.522         yes       1.00000    4.282        4.282        0.000        4.282        0.000
 36     2977.830        3010.586         yes       1.00000    4.304        4.304        0.000        4.304        0.000
 37     2978.270        3011.031         yes       1.00000    4.304        4.304        0.000        4.304        0.000
 38     3001.850        3034.870         yes       1.00000    4.339        4.339        0.000        4.339        0.000
 39     3018.660        3051.865         yes       1.00000    4.363        4.363        0.000        4.363        0.000
 40     3052.650        3086.229         yes       1.00000    4.412        4.412        0.000        4.412        0.000
 41     3063.960        3097.664         yes       1.00000    4.428        4.428        0.000        4.428        0.000
 42     3081.730        3115.629         yes       1.00000    4.454        4.454        0.000        4.454        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  54.08495       The ln(Q)    3.99056
    H vibration       83.54424   (kcal/mol)    349.54910     (kJ/mol)         0.13313610    (hartree)
    U vibration       83.54424   (kcal/mol)    349.54910     (kJ/mol)         0.13313610    (hartree)
           ZPE        80.95130   (kcal/mol)    338.70026     (kJ/mol)         0.12900400    (hartree)
    S vibration       17.14395  (cal/mol*K)     71.73030    (J/mol*K)         0.00002732  (hartree/K)
   Cv vibration       20.28275  (cal/mol*K)     84.86302    (J/mol*K)         0.00003232  (hartree/K)
    G vibration       78.43277   (kcal/mol)    328.16271     (kJ/mol)         0.12499046    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     851126764547848.87500       The ln(Q)   39.41080
        H total       85.91418   (kcal/mol)    359.46494     (kJ/mol)         0.13691284    (hartree)
        U total       85.32170   (kcal/mol)    356.98598     (kJ/mol)         0.13596866    (hartree)
       Cv total       26.24437  (cal/mol*K)    109.80644    (J/mol*K)         0.00004182  (hartree/K)
           ZPE        80.95130   (kcal/mol)    338.70026     (kJ/mol)         0.12900400    (hartree)
        S total       85.47808  (cal/mol*K)    357.64028    (J/mol*K)         0.00013622  (hartree/K)
        G total       61.02138   (kcal/mol)    255.31345     (kJ/mol)         0.09724367    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.13596866 (hartree)
                       Thermal correction to Enthalpy :   0.13691284 
              Thermal correction to Gibbs Free Energy :   0.09629948 (hartree)
              ZPE correction to the Electronic Energy :   0.12900400 (hartree)


